name: "Publish VSCode Extension"
description: "Package and publish a VSCode extension to the marketplace"
inputs:
  vscode-marketplace-pat:
    description: "VSCode Marketplace Personal Access Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Package VSCode Extension
      run: npx vsce package
      shell: bash
    - name: Publish VSCode Extension
      run: npx vsce publish -p ${{ inputs.vscode-marketplace-pat }}
      shell: bash
